id: P237D57AD
initial_creation_type: input
source_metadata:
  title: Trulshik Rinpoche Series
  language: it
  description: Texts by and about Kyabje Trulshik Rinpoche, Ngawang Chökyi Lodrö ('khrul
    zhig ngag dbang chos kyi blo gros, 1924–2011), one of the teachers of His Holiness
    the Fourteenth Dalai Lama.
  volume:
    6dd30676e62a4f4a995247597fb4e55c:
      title: Advice for Retreat
      parent: Advice
    aeaeaa8df27546f4ad6c7206b836e29e:
      title: Advice for Tenzin Jamchen
      parent: Advice
    301c45af5bb44914ac675164c6e08810:
      title: Advice in Four Lines
      parent: Advice
    2fd5e602ed6749a2948ebd733330d521:
      title: A Prayer for Translators
      parent: Aspiration Prayers
    d6b145e80bb445ea84d8fd0f5e82b3b4:
      title: A Prayer for the Spread of Kyabje Dilgo Khyentse Rinpoche’s Termas
      parent: Aspiration Prayers
    409e48d002f643f5bc676c243ea191c7:
      title: Prayer of the View, Meditation and Conduct
      parent: Aspiration Prayers
    6cebaa8d3adb484896693b038d089073:
      title: Profound Prayer of Aspiration
      parent: Aspiration Prayers
    31652f4815e64d28aff6e96b1eb6b432:
      title: 'The Quintessential Blessing: A Guru Yoga'
      parent: Guru Yoga
    2df36dabb9f14f5d86e578972bf8d3ca:
      title: 'Granting the Wish for Immortality: A Prayer for the Long Life of Dzarong
        Trulshik Rinpoche, the Representative of Guru Rinpoche'
      parent: Long Life Prayers
    4e8a218c07f2487ebff6cb9dfa6877d4:
      title: Long Life Prayer for Alak Zenkar Rinpoche
      parent: Long Life Prayers
    ba88bb73cd7f4ec5940fcf80db061e08:
      title: Long Life Prayer for Kyabje Dzarong Trulshik Rinpoche
      parent: Long Life Prayers
    8c450415ae38441d80fe701c69c14721:
      title: Long Life Prayer for Lodi Gyari Rinpoche
      parent: Long Life Prayers
    9240b1ce0a48411ca293b841aa3e2b85:
      title: Long Life Prayer for Mayum Tsering Wangmo
      parent: Long Life Prayers
    c23f7991040d45c7ab5df85fb96cd02e:
      title: Prayer for the Long Life of Chökyi Nyima Rinpoche
      parent: Long Life Prayers
    022ad8748ff546afa6f9a78753ffab44:
      title: Prayer for the Long Life of Dilgo Khyentsé II of Shechen, Urgyen Tenzin
        Jigme Lhundrup
      parent: Long Life Prayers
    7d261ca54aff46a98d5e24314bc4d90c:
      title: Prayer for the Long Life of His Holiness the Fourteenth Dalai Lama
      parent: Long Life Prayers
    a9904784b210472fa70dd3a3e40a303e:
      title: Prayer for the Long Life of Sogyal Rinpoche—chimé kunnyé
      parent: Long Life Prayers
    ec091bfcbb6d4b71abfbfff72c406cec:
      title: Prayer for the Long Life of Sogyal Rinpoche—sönam jewé
      parent: Long Life Prayers
    d2c52d3528274c25ad9a08c65996eb49:
      title: Prayer for the Long Life of Taklung Tsetrul Rinpoche
      parent: Long Life Prayers
    21155699d7184f8782a33628d95387e9:
      title: The Attainment of Immortality
      parent: Long Life Prayers
    1f1d7950315142f4aff9bcd4163f444a:
      title: A Homage to His Holiness the Dalai Lama
      parent: Praise
    2b364e3b28d5426987e6cc929ec6318b:
      title: Verses of Homage
      parent: Praise
    076bead494c2431d91ce3f3a6da82fac:
      title: Verses of Homage to the Buddhas and Bodhisattvas Together with their
        Mantras
      parent: Praise
    b348d3fa592e4178b4897af8466956f2:
      title: A Record of the Successive Incarnations
      parent: Prayers
    418957a6b99b48ee8bd85dbea8e97d0c:
      title: 'Gateway for the Faithful: A Supplication Recalling the Lives and Liberation
        of Kyabje Trulshik Rinpoche, Ngawang Chökyi Lodrö'
      parent: Prayers
    afbf2dfab4a343418f0148b54d41d5db:
      title: A Brief Daily Practice of Damdrip Nyepa Kunsel
      parent: Sādhanas
    dd1cdd254bae4e1e88a47a04e1e2cbfe:
      title: Prayer for the Swift Rebirth of Kyabjé Trulshik Rinpoche
      parent: Swift Rebirth Prayers
created_at: '2022-03-01T01:52:59.293117'
last_modified_at: '2022-03-01T01:52:59.293121'
